---
title: "Project Code"
output: html_document
date: "2024-12-04"
---

```{r}
#Loading the Libraries
library(arrow)
library(dplyr)
library(ggplot2)
library(tidyr)
library(shiny)
library(caret)
library(lattice)
library(tidyverse)
```



```{r}
metadata <- read_csv("https://intro-datascience.s3.us-east-2.amazonaws.com/SC-data/data_dictionary.csv")
```


```{r}
static_house_url <- "https://intro-datascience.s3.us-east-2.amazonaws.com/SC-data/static_house_info.parquet"
static_house_data <- read_parquet(static_house_url)
```


```{r}
ncol(static_house_data)
```


```{r}
static_house_data <- static_house_data[, !apply(static_house_data, 2, function(x) all(x == "None"))]


# List of columns to remove  (unnecessary columns)
columns_to_remove <- c("upgrade",                                      
                        "weight",                                       
                        "applicability",                                
                        "in.ahs_region",                                
                        "in.ashrae_iecc_climate_zone_2004",             
                        "in.ashrae_iecc_climate_zone_2004_2_a_split",   
                        "in.census_division",                           
                        "in.census_division_recs",                      
                        "in.census_region",                             
                        "in.corridor",                                  
                        "in.door_area",                                 
                        "in.doors",                                     
                        "in.eaves",                                     
                        "in.emissions_electricity_folders",             
                        "in.emissions_electricity_units",               
                        "in.emissions_electricity_values_or_filepaths",   
                        "in.emissions_fossil_fuel_units",               
                        "in.emissions_fuel_oil_values",                 
                        "in.emissions_natural_gas_values",              
                        "in.emissions_propane_values",                  
                        "in.emissions_scenario_names",                  
                        "in.emissions_types",                           
                        "in.emissions_wood_values",                     
                        "in.generation_and_emissions_assessment_region",  
                        "in.geometry_building_type_acs",                
                        "in.geometry_building_type_height",             
                        "in.geometry_building_type_recs",               
                        "in.geometry_story_bin",                        
                        "in.holiday_lighting",                          
                        "in.hot_water_distribution",                    
                        "in.hvac_system_is_faulted",                    
                        "in.interior_shading",                          
                        "in.lighting_interior_use",                     
                        "in.lighting_other_use",                        
                        "in.location_region",                           
                        "in.natural_ventilation",                       
                        "in.neighbors",                                 
                        "in.plug_loads",                                
                        "in.radiant_barrier",                           
                        "in.schedules",                                 
                        "in.simulation_control_timestep",               
                        "in.state",                                     
                        "in.units_represented",                         
                        "in.water_heater_in_unit",                      
                        "upgrade.hvac_cooling_efficiency",
                       "in.simulation_control_run_period_begin_day_of_month",
                       "upgrade.geometry_foundation_type",
                       "in.simulation_control_run_period_begin_month",
                       "in.simulation_control_run_period_calendar_year",
                       "in.simulation_control_run_period_end_day_of_month",
                       "in.simulation_control_run_period_end_month",
                       "upgrade.insulation_roof","upgrade.water_heater_efficiency",
                       "upgrade.hvac_cooling_efficiency","upgrade.infiltration_reduction",
                       "upgrade.geometry_foundation_type","upgrade.clothes_dryer",
                       "upgrade.insulation_ceiling","upgrade.ducts","upgrade.hvac_heating_type","upgrade.insulation_wall","upgrade.insulation_foundation_wall","upgrade.hvac_heating_efficiency","upgrade.cooking_range","in.city","in.clothes_washer_presence")  

# Remove specified columns from the dataset  
static_house_data <- static_house_data[, !names(static_house_data) %in% columns_to_remove]
ncol(static_house_data)
```


```{r}
binary_columns <- c(
  "in.cooling_setpoint_has_offset", "in.has_pv", "in.heating_setpoint_has_offset",
  "in.hvac_has_ducts", "in.hvac_has_zonal_electric_heating", "in.misc_freezer",
  "in.misc_gas_fireplace", "in.misc_gas_grill", "in.misc_gas_lighting", "in.misc_pool",
  "in.misc_pool_pump", "in.misc_well_pump", "in.tenure", "in.vacancy_status"
)

binary_columns_2 <- list(
  in.cooling_setpoint_has_offset = c("No", "Yes"),
  in.has_pv = c("No", "Yes"),
  in.heating_setpoint_has_offset = c("No", "Yes"),
  in.hvac_has_ducts = c("No", "Yes"),
  in.hvac_has_zonal_electric_heating = c("No", "Yes"),
  in.misc_freezer = c("None", "EF 12, National Average"),
  in.misc_gas_fireplace = c("None", "Gas Fireplace"),
  in.misc_gas_grill = c("None", "Gas Grill"),
  in.misc_gas_lighting = c("None", "Gas Lighting"),
  in.misc_pool = c("None", "Has Pool"),
  in.misc_pool_pump = c("None", "1.0 HP Pump"),
  in.misc_well_pump = c("None", "Typical Efficiency"),
  in.tenure = c("Renter", "Owner"),
  in.vacancy_status = c("Vacant", "Occupied")
)

static_house_data$in.clothes_dryer <- gsub("Gas", "Propane", static_house_data$in.clothes_dryer)
static_house_data$in.clothes_dryer <- gsub("Propane, 80% Usage", "Propane, 120% Usage", static_house_data$in.clothes_dryer)
static_house_data$in.clothes_dryer <- gsub("Propane, 100% Usage", "Propane, 120% Usage", static_house_data$in.clothes_dryer)

static_house_data$in.cooking_range <- gsub("Gas", "Propane", static_house_data$in.cooking_range)
static_house_data$in.cooking_range <- gsub("Propane, 80% Usage", "Propane, 120% Usage", static_house_data$in.cooking_range)
static_house_data$in.cooking_range <- gsub("Propane, 100% Usage", "Propane, 120% Usage", static_house_data$in.cooking_range)
static_house_data$in.heating_fuel <- gsub("Fuel Oil", "Other Fuel", static_house_data$in.heating_fuel)
static_house_data$in.heating_fuel <- gsub("Propane", "Other Fuel", static_house_data$in.heating_fuel)
static_house_data$in.heating_fuel <- gsub("Natural Gas", "Other Fuel", static_house_data$in.heating_fuel)

static_house_data$in.ducts[static_house_data$in.ducts == "None"] <- NA
static_house_data$in.insulation_ceiling[static_house_data$in.insulation_ceiling == "None"] <- "Uninsulated"
static_house_data$in.insulation_floor[static_house_data$in.insulation_floor == "None"] <- "Uninsulated"
static_house_data$in.heating_fuel[static_house_data$in.heating_fuel == "None"] <- NA
static_house_data$in.insulation_foundation_wall[static_house_data$in.insulation_foundation_wall == "None"] <- "Uninsulated"
static_house_data$in.insulation_rim_joist[static_house_data$in.insulation_rim_joist == "None"] <- "Uninsulated"
static_house_data$in.pv_system_size[static_house_data$in.pv_system_size == "None"] <- 0
static_house_data$in.insulation_slab[static_house_data$in.insulation_slab == "None"] <- "Uninsulated"
# Update in.hvac_cooling_type based on the starting text of in.hvac_cooling_efficiency
static_house_data$in.hvac_cooling_type <- ifelse(
  startsWith(static_house_data$in.hvac_cooling_efficiency, "Heat pump"),
  "Heat Pump",
  ifelse(
    startsWith(static_house_data$in.hvac_cooling_efficiency, "AC"),
    "Central AC",
    ifelse(
      startsWith(static_house_data$in.hvac_cooling_efficiency, "Room AC"),
      "Room AC",
      static_house_data$in.hvac_cooling_type  # Retain original value if no match
    )
  )
)

none_columns <- function(data, columns_to_convert, custom_levels) {
  for (column_name in columns_to_convert) {
    if (!column_name %in% colnames(data)) {
      warning(paste("Column", column_name, "not found in the data frame. Skipping."))
      next
    }
    if (!is.character(data[[column_name]])) {
      warning(paste("Column", column_name, "is not a character column. Skipping."))
      next
    }
    if (!column_name %in% names(custom_levels)) {
      warning(paste("No custom levels provided for column", column_name, "Skipping."))
      next
    }
    levels <- custom_levels[[column_name]]
    data[[column_name]] <- factor(data[[column_name]], levels = levels, labels = seq_along(levels) - 1)
  }
  return(data)
}

valid_none_columns <- c(
  "in.ceiling_fan", "in.clothes_dryer", "in.clothes_washer", "in.dishwasher",
  "in.geometry_attic_type", "in.geometry_garage", "in.hvac_cooling_efficiency",
  "in.hvac_cooling_partial_space_conditioning", "in.hvac_cooling_type", "in.hvac_heating_efficiency",
  "in.hvac_heating_type", "in.hvac_heating_type_and_fuel", "in.misc_extra_refrigerator",
  "in.misc_hot_tub_spa", "in.misc_pool_heater", "in.refrigerator"
)

valid_none_columns_2 <- list(
  in.ceiling_fan = c("None", "Standard Efficiency, No Usage", "Standard Efficiency"),
  in.clothes_washer = c(
    "None", "EnergyStar, 80% Usage", "EnergyStar, 100% Usage",
    "EnergyStar, 120% Usage", "Standard, 80% Usage", "Standard, 100% Usage", "Standard, 120% Usage"
  ),
  in.clothes_dryer = c(
    "None", "Propane, 120% Usage", "Electric, 80% Usage", "Electric, 100% Usage", "Electric, 120% Usage"
  ),
  in.misc_extra_refrigerator = c("None", "EF 19.9", "EF 17.6", "EF 15.9", "EF 10.5", "EF 10.2", "EF 6.7"),
  in.misc_hot_tub_spa = c("None", "Gas", "Electric"),
  in.misc_pool_heater = c("None", "Solar", "Gas", "Electric"),
  in.refrigerator = c(
    "None", "EF 19.9, 100% Usage", "EF 17.6, 100% Usage", "EF 15.9, 100% Usage",
    "EF 10.5, 100% Usage", "EF 10.2, 100% Usage", "EF 6.7, 100% Usage"
  ),
  in.hvac_cooling_type = c("None", "Room AC", "Heating Pump", "Central AC"),
  in.hvac_heating_efficiency = c( "ASHP, SEER 10, 6.2 HSPF","ASHP, SEER 13, 7.7 HSPF","ASHP, SEER 15, 8.5 HSPF","Electric Baseboard, 100% Efficiency","Electric Boiler, 100% AFUE","Electric Furnace, 100% AFUE","Electric Wall Furnace, 100% AFUE","Fuel Boiler, 76% AFUE","Fuel Boiler, 80% AFUE","Fuel Boiler, 90% AFUE","Fuel Furnace, 60% AFUE","Fuel Furnace, 76% AFUE","Fuel Furnace, 80% AFUE","Fuel Furnace, 92.5% AFUE","Fuel Wall/Floor Furnace, 60% AFUE","Fuel Wall/Floor Furnace, 68% AFUE","None","Other","Shared Heating"
  )
)

convert_without_none_function <- function(data, columns_to_convert, custom_levels) {
  for (column_name in columns_to_convert) {
    if (!column_name %in% colnames(data)) {
      warning(paste("Column", column_name, "not found in the data frame. Skipping."))
      next
    }
    if (!is.character(data[[column_name]])) {
      warning(paste("Column", column_name, "is not a character column. Skipping."))
      next
    }
    if (!column_name %in% names(custom_levels)) {
      warning(paste("No custom levels provided for column", column_name, "Skipping."))
      next
    }
    levels <- custom_levels[[column_name]]
    data[[column_name]] <- factor(data[[column_name]], levels = levels, labels = seq_along(levels))
  }
  return(data)
}

invalid_none_columns_to_convert <- c(
  "in.building_america_climate_zone", "in.cooking_range", "in.ducts", "in.geometry_floor_area",
  "in.geometry_foundation_type", "in.geometry_wall_exterior_finish", "in.geometry_wall_type",
  "in.heating_fuel", "in.hot_water_fixtures", "in.insulation_ceiling", "in.insulation_floor",
  "in.insulation_foundation_wall", "in.insulation_rim_joist", "in.insulation_roof", "in.insulation_slab",
  "in.insulation_wall", "in.lighting", "in.roof_material", "in.usage_level", "in.water_heater_efficiency",
  "in.water_heater_fuel", "in.window_areas", "in.windows"
)

invalid_none_custom <- list(
  in.building_america_climate_zone = c("Marine", "Mixed-Humid", "Mixed-Dry", "Hot-Humid", "Hot-Dry", "Cold", "Very Cold"),
  in.cooking_range = c("Propane, 120% Usage", "Electric, 80% Usage", "Electric, 100% Usage", "Electric, 120% Usage", "None"),
  in.heating_fuel = c("Other Fuel", "Electricity", "None"),
  in.hot_water_fixtures = c("50% Usage", "100% Usage", "200% Usage"),
  in.insulation_ceiling = c("R-49", "R-38", "R-30", "R-19", "R-13", "R-7", "Uninsulated"),
  in.insulation_floor = c("Ceiling R-30", "Ceiling R-19", "Ceiling R-13", "Uninsulated"),
  in.ducts = c(
    "0% Leakage, Uninsulated", "10% Leakage, R-8", "10% Leakage, R-6,", "10% Leakage, R-4",
    "20% Leakage, R-8", "30% Leakage, R-8", "20% Leakage, R-6", "20% Leakage, R-4",
    "30% Leakage, R-6", "10% Leakage, Uninsulated", "20% Leakage, Uninsulated", 
    "30% Leakage, R-4", "30% Leakage, Uninsulated", "None"
  ),
  in.geometry_floor_area = c("0-499", "500-749", "750-999", "1000-1499", "1500-1999", "2000-2499", "2500-2999", "3000-3999", "4000+"),
  in.geometry_foundation_type = c("Ambient", "Slab", "Unvented Crawlspace", "Unheated Basement", "Vented Crawlspace", "Heated Basement"),
  in.geometry_wall_exterior_finish = c(
    "Aluminum, Light", "Vinyl, Light", "Stucco, Light", "Brick, Light", "Fiber-Cement, Light",
    "Stucco, Medium/Dark", "Brick, Medium/Dark", "Wood, Medium/Dark", "Shingle, Composition, Medium", 
    "Shingle, Asbestos, Medium", "None"
  ),
  in.geometry_wall_type = c("Concrete", "Steel Frame", "Brick", "Wood Frame"),
  in.insulation_foundation_wall = c("Wall R-15, Exterior", "Wall R-10, Exterior", "Wall R-5, Exterior", "Uninsulated"),
  in.insulation_rim_joist = c("Uninsulated", "R-5, Exterior", "R-10, Exterior", "R-15, Exterior"),
  in.insulation_roof = c(
    "Finished, R-49", "Finished, R-38", "Finished, R-30", "Finished, R-19", "Finished, R-13", 
    "Finished, R-7", "Finished, Uninsulated", "Unfinished, Uninsulated"
  ),
  in.insulation_slab = c(
    "2ft R10 Perimeter, Vertical", "2ft R10 Under, Horizontal", "2ft R5 Perimeter, Vertical", 
    "2ft R5 Under, Horizontal", "Uninsulated"
  ),
  in.water_heater_fuel = c("Natural Gas", "Fuel Oil", "Propane", "Electricity", "Other Fuel"),
  in.window_areas = c(
    "F6 B6 L6 R6", "F9 B9 L9 R9", "F12 B12 L12 R12", "F15 B15 L15 R15", 
    "F18 B18 L18 R18", "F30 B30 L30 R30"
  ),
  in.windows = c(
    "Triple, Low-E, Non-metal, Air, L-Gain", "Double, Low-E, Non-metal, Air, M-Gain",
    "Double, Clear, Non-metal, Air, Exterior Clear Storm", "Double, Clear, Non-metal, Air",
    "Double, Clear, Metal, Air, Exterior Clear Storm", "Double, Clear, Metal, Air",
    "Single, Clear, Non-metal", "Single, Clear, Non-metal, Exterior Clear Storm",
    "Single, Clear, Metal", "Single, Clear, Metal, Exterior Clear Storm"
  ),
  in.insulation_wall = c(
    "Brick, 12-in, 3-wythe, R-19", "CMU, 6-in Hollow, R-19", "Wood Stud, R-19", 
    "Brick, 12-in, 3-wythe, R-15", "CMU, 6-in Hollow, R-15", "Wood Stud, R-15",
    "Brick, 12-in, 3-wythe, R-11", "CMU, 6-in Hollow, R-11", "Wood Stud, R-11",
    "Brick, 12-in, 3-wythe, R-7", "CMU, 6-in Hollow, R-7", "Wood Stud, R-7",
    "Brick, 12-in, 3-wythe, Uninsulated", "CMU, 6-in Hollow, Uninsulated", "Wood Stud, Uninsulated"
  ),
  in.lighting = c("100% LED", "100% CFL", "100% Incandescent"),
  in.roof_material = c("Tile, Concrete", "Tile, Clay or Ceramic", "Slate", "Wood Shingles", "Composition Shingles", "Asphalt Shingles, Medium", "Metal, Dark"),
  in.usage_level = c("Low", "Medium", "High"),
  in.water_heater_efficiency = c(
    "Natural Gas Tankless", "Propane Tankless", "FIXME Fuel Oil Indirect", "Fuel Oil Indirect", 
    "Natural Gas Premium", "Propane Premium", "Fuel Oil Premium", "Natural Gas Standard", 
    "Propane Standard", "Fuel Oil Standard", "Electric Tankless", "Electric Premium", 
    "Electric Standard", "Electric Heat Pump, 80 gal", "Other Fuel"
  )
)

cooling_setpoint_function <- function(data, column_name) {
  # Define the mapping of characters to integers
  mapping <- c(
    "Day Setup" = 8, "Day Setup +1h" = 9, "Day Setup +2h" = 10, "Day Setup +3h" = 11,
    "Day Setup +4h" = 12, "Day Setup +5h" = 13, "Day Setup -1h" = 7, "Day Setup -2h" = 6,
    "Day Setup -3h" = 5, "Day Setup -4h" = 4, "Day Setup -5h" = 3, "Day Setup and Night Setback" = 17,
    "Day Setup and Night Setback +1h" = 18, "Day Setup and Night Setback +2h" = 19,
    "Day Setup and Night Setback +3h" = 20, "Day Setup and Night Setback +4h" = 21,
    "Day Setup and Night Setback +5h" = 22, "Day Setup and Night Setback -1h" = 16,
    "Day Setup and Night Setback -2h" = 15, "Day Setup and Night Setback -3h" = 14,
    "Day Setup and Night Setback -4h" = 13, "Day Setup and Night Setback -5h" = 12,
    "Day and Night Setup" = 17, "Day and Night Setup +1h" = 18, "Day and Night Setup +2h" = 19,
    "Day and Night Setup +3h" = 20, "Day and Night Setup +4h" = 21, "Day and Night Setup +5h" = 22,
    "Day and Night Setup -1h" = 16, "Day and Night Setup -2h" = 15, "Day and Night Setup -3h" = 14,
    "Day and Night Setup -4h" = 13, "Day and Night Setup -5h" = 12, "Night Setback" = 9,
    "Night Setback +1h" = 10, "Night Setback +2h" = 11, "Night Setback +3h" = 12,
    "Night Setback +4h" = 13, "Night Setback +5h" = 14, "Night Setback -1h" = 8,
    "Night Setback -2h" = 7, "Night Setback -3h" = 6, "Night Setback -4h" = 5,
    "Night Setback -5h" = 4, "Night Setup" = 9, "Night Setup +1h" = 10, "Night Setup +2h" = 11,
    "Night Setup +3h" = 12, "Night Setup +4h" = 13, "Night Setup +5h" = 14, "Night Setup -1h" = 8,
    "Night Setup -2h" = 7, "Night Setup -3h" = 6, "Night Setup -4h" = 5, "Night Setup -5h" = 4,
    "None" = 0
  )

  if (!column_name %in% colnames(data)) {
    stop(paste("Column", column_name, "not found in the data frame."))
  }

  data[[column_name]] <- sapply(data[[column_name]], function(value) {
    if (is.null(value) || is.na(value) || value == "") {
      return(NA)
    }
    if (value %in% names(mapping)) {
      return(mapping[value])
    } else {
      warning(paste("Unrecognized value:", value))
      return(NA)
    }
  })
  data[[column_name]] <- as.numeric(data[[column_name]])
  return(data)
}

heating_setpoint_function <- function(data, column_name) {
  mapping <- c(
    "Day" = 8, "Day +1h" = 9, "Day +2h" = 10, "Day +3h" = 11, "Day +4h" = 12,
    "Day +5h" = 13, "Day -1h" = 7, "Day -2h" = 6, "Day -3h" = 5, "Day -4h" = 4,
    "Day -5h" = 3, "Day and Night" = 17, "Day and Night +1h" = 18, "Day and Night +2h" = 19,
    "Day and Night +3h" = 20, "Day and Night +4h" = 21, "Day and Night +5h" = 22,
    "Day and Night -1h" = 16, "Day and Night -2h" = 15, "Day and Night -3h" = 14,
    "Day and Night -4h" = 13, "Day and Night -5h" = 12, "Night" = 9, "Night +1h" = 10,
    "Night +2h" = 11, "Night +3h" = 12, "Night +4h" = 13, "Night +5h" = 14,
    "Night -1h" = 8, "Night -2h" = 7, "Night -3h" = 6, "Night -4h" = 5, "Night -5h" = 4,
    "None" = 0
  )

  if (!column_name %in% colnames(data)) {
    stop(paste("Column", column_name, "not found in the data frame."))
  }

  data[[column_name]] <- sapply(data[[column_name]], function(value) {
    if (is.null(value) || is.na(value) || value == "") {
      return(NA)
    }
    if (value %in% names(mapping)) {
      return(mapping[value])
    } else {
      warning(paste("Unrecognized value:", value))
      return(NA)
    }
  })
  data[[column_name]] <- as.numeric(data[[column_name]])
  return(data)
}
cleaning_integer_function <- function(data, columns_to_clean) {
  for (column_name in names(columns_to_clean)) {
    if (!column_name %in% colnames(data)) {
      warning(paste("Column", column_name, "not found in the data frame. Skipping."))
      next
    }
    if (!is.character(data[[column_name]]) && !is.numeric(data[[column_name]])) {
      warning(paste("Column", column_name, "is not character or numeric. Skipping."))
      next
    }
    characters_to_remove <- columns_to_clean[[column_name]]
    for (char in characters_to_remove) {
      data[[column_name]] <- gsub(char, "", data[[column_name]])
    }
    data[[column_name]] <- as.integer(data[[column_name]])
  }
  return(data)
}

integers_columns_to_be_cleaned <- list(
  "in.bathroom_spot_vent_hour" = c("Hour"),
  "in.cooling_setpoint" = c("F"),
  "in.cooling_setpoint_offset_magnitude" = c("F"),
  "in.heating_setpoint" = c("F"),
  "in.heating_setpoint_offset_magnitude" = c("F"),
  "in.plug_load_diversity" = c("%"),
  "in.range_spot_vent_hour" = c("Hour"),
  "in.infiltration" = c(" ACH50"),
  "in.occupants" = c("+"),
  "in.pv_system_size" = c(" kWDC")
)

factor_conversion <- function(data, columns_to_convert, custom_levels = NULL) {
  for (column_name in columns_to_convert) {
    if (!column_name %in% colnames(data)) {
      warning(paste("Column", column_name, "not found in the data frame. Skipping."))
      next
    }
    if (!is.character(data[[column_name]])) {
      warning(paste("Column", column_name, "is not a character column. Skipping."))
      next
    }
    unique_values <- unique(data[[column_name]])
    if (length(unique_values) != 2) {
      warning(paste("Column", column_name, "does not have exactly two unique values. Skipping."))
      next
    }
    if (!is.null(custom_levels) && column_name %in% names(custom_levels)) {
      levels <- custom_levels[[column_name]]
    } else {
      levels <- sort(unique_values)
    }
    data[[column_name]] <- factor(data[[column_name]], levels = levels, labels = c(0, 1), ordered = TRUE)
  }
  return(data)
}

static_house_data <- cleaning_integer_function(static_house_data, integers_columns_to_be_cleaned)
static_house_data <- factor_conversion(static_house_data, binary_columns, binary_columns_2)
static_house_data <- none_columns(static_house_data, valid_none_columns, valid_none_columns_2)
static_house_data <- convert_without_none_function(static_house_data, invalid_none_columns_to_convert, invalid_none_custom)
static_house_data <- cooling_setpoint_function(static_house_data, "in.cooling_setpoint_offset_period")
static_house_data <- heating_setpoint_function(static_house_data, "in.heating_setpoint_offset_period")
```


```{r}
base_url <- "https://intro-datascience.s3.us-east-2.amazonaws.com/SC-data/weather/2023-weather-data/"

county_codes <- unique(static_house_data$in.county) 

county <- function(county_code) {
  url <- paste0(base_url, county_code, ".csv")
  data <- read.csv(url)
  return(data)
}
county_list <- lapply(county_codes, county)
names(county_list) <- county_codes

#i just wanted to test if the dataset is properly loaded so tried out for two county codes
head(county_list[["G4500830"]])
head(county_list[["G4500410"]])
```

```{r}
base_url <- "https://intro-datascience.s3.us-east-2.amazonaws.com/SC-data/weather/2023-weather-data/"
county_codes <- unique(static_house_data$in.county)
urls <- paste0(base_url, county_codes, ".csv")
urls
```


#only for the month of july:
```{r}
#here, i have first made a function to take only july data into consideration
library(lubridate)
july_weather <- function(data) {
data$date_time <- ymd_hms(data$date_time)
data <- data[month(data$date_time)==7,]
return(data)
}

counties <- names(county_list)

julyweather <- lapply(county_list[counties], july_weather)

for (i in seq_along(julyweather)) {
julyweather[[i]]$county_code <- counties[i]}

july_weatherdata <- do.call(rbind, julyweather)

rownames(july_weatherdata) <-NULL

```

```{r}
#fixing null values- i did it with linear interpolation
library(imputeTS)

july_weatherdata[july_weatherdata == 0.00] <- NA
for (col_name in colnames(july_weatherdata)) {
  if (is.numeric(july_weatherdata[[col_name]])) {  
    july_weatherdata[[col_name]] <- na_interpolation(july_weatherdata[[col_name]], option = "linear")
  }
}

#there were trailing zeros so i removed them too
for (col_name in colnames(july_weatherdata)) {
  if (is.numeric(july_weatherdata[[col_name]])) {  
    july_weatherdata[[col_name]] <- as.numeric(format(july_weatherdata[[col_name]], trim = TRUE, scientific = FALSE, digits = 5))
  }
}
head(july_weatherdata)

```

```{r}
#fixing the column name

columnnames <- function(names) {
  names <- gsub("[^a-zA-Z0-9]", "_", names) 
  names <- tolower(names)  
  return(names)
}

colnames(july_weatherdata) <- columnnames(colnames(july_weatherdata))
colnames(july_weatherdata)

#i still didnt like how the column names looked so i manually typed in
colnames(july_weatherdata) <- c(
  "date_time",          
  "dry_bulb_temperature",      
  "relative_humidity",           
  "wind_speed",    
  "wind_direction", 
  "global_horizontal_radiation",      
  "direct_normal_radiation",       
  "diffuse_horizontal_radiation",      
  "county_code"        
)

colnames(july_weatherdata)

```


#for may june july daily
```{r}
#this is the same code that i did for the july data but here i have taken three months in consideration that is may, june, july
library(lubridate)

mjj_data <- function(data) {
  data$date_time <- ymd_hms(data$date_time)
  data <- data[month(data$date_time) %in% c(5, 6, 7), ]
  return(data)
}

counties <- names(county_list)

mjj_list <- lapply(county_list[counties], mjj_data)

for (i in seq_along(mjj_list)) {
  mjj_list[[i]]$county_code <- counties[i]}

mjj_weatherdata <- do.call(rbind, mjj_list)
head(mjj_weatherdata)

rownames(mjj_weatherdata) <- NULL

```

```{r}
#fixing null values: again i did interpolation since we are dealing with weather data
library(imputeTS)

mjj_weatherdata[mjj_weatherdata == 0.00] <- NA

for (col_name in colnames(mjj_weatherdata)) {
  if (is.numeric(mjj_weatherdata[[col_name]])) {  
    mjj_weatherdata[[col_name]] <- na_interpolation(mjj_weatherdata[[col_name]], option = "linear")
  }
}

for (col_name in colnames(mjj_weatherdata)) {
  if (is.numeric(mjj_weatherdata[[col_name]])) {  
    mjj_weatherdata[[col_name]] <- as.numeric(format(mjj_weatherdata[[col_name]], trim = TRUE, scientific = FALSE, digits = 5))
  }
}
head(mjj_weatherdata)
```

```{r}
#fixing the column name

columnnames <- function(names) {
  names <- gsub("[^a-zA-Z0-9]", "_", names)  
  names <- tolower(names) 
  return(names)
}

colnames(mjj_weatherdata) <- columnnames(colnames(mjj_weatherdata))
colnames(mjj_weatherdata)

#i still didnt like how the column names looked so i manually typed in
colnames(mjj_weatherdata) <- c(
  "date_time",          
  "dry_bulb_temperature",     
  "relative_humidity",          
  "wind_speed",   
  "wind_direction", 
  "global_horizontal_radiation",     
  "direct_normal_radiation",      
  "diffuse_horizontal_radiation",      
  "county_code"        
)

colnames(mjj_weatherdata)
```

```{r}
#converting hourly into daily basis
library(dplyr)
library(lubridate)

mjj_weatherdata$date_time <- ymd_hms(mjj_weatherdata$date_time)
mjj_weatherdata$date <- as.Date(mjj_weatherdata$date_time)

mjj_weather_data <- mjj_weatherdata %>%
  group_by(county_code, date) %>%
  summarise(
    dry_bulb_temperature = mean(dry_bulb_temperature, na.rm = TRUE),
    relative_humidity = mean(relative_humidity, na.rm = TRUE),
    wind_speed = mean(wind_speed, na.rm = TRUE),
    wind_direction = mean(wind_direction, na.rm = TRUE),
    global_horizontal_radiation = mean(global_horizontal_radiation, na.rm = TRUE),
    direct_normal_radiation = mean(direct_normal_radiation, na.rm = TRUE),
    diffuse_horizontal_radiation = mean(diffuse_horizontal_radiation, na.rm = TRUE),
    .groups = "drop" #needed to do this to avoid grouping in the result
  )

head(mjj_weather_data)
```

```{r}
#i saw that there were 46 rows for each counties which had aggregated NA values so i am removing those as well
MayJuneJuly_weatherdata <- mjj_weather_data[!is.na(mjj_weather_data$date), ]
head(MayJuneJuly_weatherdata)

```


```{r}
merged_data <- merge(static_house_data, july_weatherdata, by.x = "in.county",
                     by.y = "county_code", all = FALSE)  
```


```{r}
######RUN THISSSSS FOR JULY DATA ###########

library(arrow)
library(dbplyr)
library(dplyr)
library(tidyverse)
library(data.table)
library(arrow)
library(dplyr)


energy_data <- read_parquet("~/Documents/Introduction to Data science/Project/COMBINED_ENERGY_DATASET_5000_House_IDS.parquet copy")
dim(data)

# Assuming the data-set is already loaded into the variable 'data'
new_data <- energy_data %>%
  select(starts_with("out.electricity"),time,building_id)


new_data <- new_data %>%
  mutate(electricity = rowSums(select(., starts_with("out.electricity.")), na.rm = TRUE))


new_data <- new_data %>%
  mutate(time = as.POSIXct(time, format = "%Y-%m-%d %H:%M:%S")) %>%  # Convert time column to POSIXct
  filter(format(time, "%m") == "07")  # Filter for July (07)


write_parquet(new_data,"~/Documents/Introduction to Data science/Project/COMBINED_ENERGY_DATASET_5000_House_IDS_final.parquet")

```


```{r}
new_data$combined_key <- paste(new_data$building_id, new_data$time, sep = "_")
merged_data$combined_key <- paste(merged_data$bldg_id, merged_data$date_time, sep = "_")
```

```{r}
final_merged_data <- merge(new_data, merged_data, 
                           by = "combined_key",
                           all = FALSE)
```

```{r}
final_merged_data <- final_merged_data %>%
  arrange(combined_key)
```



# Adjusting for missing values using backward/forward interpolation as the missing
# values.

```{r}
library(zoo)
final_merged_data$in.ceiling_fan <- na.locf(final_merged_data$in.ceiling_fan, na.rm = FALSE)
final_merged_data$in.ceiling_fan <- na.locf(final_merged_data$in.ceiling_fan, na.rm = FALSE, fromLast = TRUE)

final_merged_data$in.ducts <- na.locf(final_merged_data$in.ducts, na.rm = FALSE)
final_merged_data$in.ducts <- na.locf(final_merged_data$in.ducts, na.rm = FALSE, fromLast = TRUE)

final_merged_data$in.hvac_cooling_type <- na.locf(final_merged_data$in.hvac_cooling_type, na.rm = FALSE)
final_merged_data$in.hvac_cooling_type <- na.locf(final_merged_data$in.hvac_cooling_type, na.rm = FALSE, fromLast = TRUE)

final_merged_data$in.hvac_heating_efficiency <- na.locf(final_merged_data$in.hvac_heating_efficiency, na.rm = FALSE)
final_merged_data$in.hvac_heating_efficiency <- na.locf(final_merged_data$in.hvac_heating_efficiency, na.rm = FALSE, fromLast = TRUE)

final_merged_data$in.ceiling_fan <- na.locf(final_merged_data$in.ceiling_fan, na.rm = FALSE)
final_merged_data$in.ceiling_fan <- na.locf(final_merged_data$in.ceiling_fan, na.rm = FALSE, fromLast = TRUE)


#Removing rows for 2 columns. 

final_merged_data <- final_merged_data %>%
  filter(!is.na(in.heating_fuel), !is.na(in.occupants))
```

# EXPLORATORY ANALYSIS

```{r}
summary_statistics <- function(data) {
  # Initialize a list to store summary statistics for each column
  summary_list <- list()
  
  # Loop through each column in the dataset
  for (col_name in names(data)) {
    # Extract the current column's data
    col_data <- data[[col_name]]
    
    # Create a template for storing statistics for the column
    # This ensures all columns have the same structure in the summary
    stats <- data.frame(
      Column = col_name,                # Name of the column
      Type = NA,                        # Data type (to be filled later)
      Mean = NA,                        # Mean (only for numerical data)
      Median = NA,                      # Median (only for numerical data)
      SD = NA,                          # Standard deviation (only for numerical data)
      Min = NA,                         # Minimum value (only for numerical data)
      Max = NA,                         # Maximum value (only for numerical data)
      Mode = NA,                        # Mode (only for categorical data)
      Unique_Values = NA,               # Number of unique values
      Most_Frequent_Count = NA,         # Frequency of the most common value (categorical only)
      Missing = sum(is.na(col_data)),   # Count of missing values
      stringsAsFactors = FALSE          # Ensure no automatic conversion to factors
    )
    
    # If the column is numeric, calculate numerical statistics
    if (is.numeric(col_data)) {
      stats$Type <- "Numeric"                           # Specify type as numeric
      stats$Mean <- mean(col_data, na.rm = TRUE)        # Calculate mean, ignoring NAs
      stats$Median <- median(col_data, na.rm = TRUE)    # Calculate median, ignoring NAs
      stats$SD <- sd(col_data, na.rm = TRUE)            # Calculate standard deviation
      stats$Min <- min(col_data, na.rm = TRUE)          # Find minimum value
      stats$Max <- max(col_data, na.rm = TRUE)          # Find maximum value
    
    # If the column is categorical (character or factor), calculate frequency-based stats
    } else if (is.character(col_data) || is.factor(col_data)) {
      stats$Type <- "Categorical"                       # Specify type as categorical
      freq_table <- table(col_data, useNA = "ifany")    # Create frequency table
      stats$Mode <- names(freq_table)[which.max(freq_table)] # Find the most frequent value
      stats$Unique_Values <- length(unique(col_data))   # Count unique values
      stats$Most_Frequent_Count <- max(freq_table)      # Count occurrences of the most common value
    
    # For other data types (e.g., dates, logical), handle them generically
    } else {
      stats$Type <- paste(class(col_data), collapse = ", ") # Combine multiple classes into one string
      stats$Unique_Values <- length(unique(col_data))       # Count unique values
    }
    
    # Add the column's stats to the summary list
    summary_list[[col_name]] <- stats
  }
  
  # Combine all individual column statistics into a single data frame
  summary_df <- do.call(rbind, summary_list) # Safely combine all rows into a data frame
  rownames(summary_df) <- NULL               # Remove row names for cleaner output
  
  # Return the summary as a data frame
  return(summary_df)
}
summary_stats <- summary_statistics(final_merged_data)

library(data.table)

# Function to compute correlation table
correlation_table <- function(data) {
  # Ensure data is a data.table
  if (!inherits(data, "data.table")) {
    data <- as.data.table(data)
  }
  
  # Select only numerical columns
  numerical_cols <- names(data)[sapply(data, is.numeric)]
  
  # Check if there are enough numerical columns
  if (length(numerical_cols) < 2) {
    stop("Not enough numerical columns to compute a correlation table.")
  }
  
  # Compute correlation matrix
  corr_matrix <- cor(data[, ..numerical_cols])
  
  # Return the correlation matrix
  return(corr_matrix)
}

# Example usage:
corr_table <- correlation_table(final_merged_data)
print(corr_table)
```


```{r}
library(data.table)

# Ensure data is a data.table
final_merged_data <- as.data.table(final_merged_data)

# Convert all categorical variables to numeric
categorical_cols <- names(final_merged_data)[sapply(final_merged_data, is.factor) | sapply(final_merged_data, is.character)]
final_merged_data[, (categorical_cols) := lapply(.SD, function(x) as.numeric(as.factor(x))), .SDcols = categorical_cols]

# Check the result
str(final_merged_data)
```
```{r}
library(BayesFactor)   # For Bayesian Linear Regression
library(xgboost)       # For XGBoost
library(randomForest)  # For Random Forest
library(plm)           # For Panel Regression
library(forecast)      # For ARIMA

# Linear Regression
linear_model_behavioural <- lm(
  electricity ~ in.cooling_setpoint + in.heating_setpoint + in.occupants +
    in.lighting + in.misc_extra_refrigerator + in.misc_pool_pump +
    in.misc_gas_fireplace + in.range_spot_vent_hour +
    in.hot_water_fixtures + in.vacancy_status,
  data = final_merged_data
)

# Display model summary
summary(linear_model_behavioural)
```


```{r}
bayesian_model_behavioural <- lmBF(
  electricity ~ in.cooling_setpoint + in.heating_setpoint + in.occupants +
    in.lighting + in.misc_extra_refrigerator + in.misc_pool_pump +
    in.misc_gas_fireplace + in.range_spot_vent_hour +
    in.hot_water_fixtures + in.vacancy_status,
  data = final_merged_data)

# Display Bayes Factor
summary(bayesian_model_behavioural)
```
```{r}
library(xgboost)

# Prepare data
x <- as.matrix(final_merged_data[, .(
  in.cooling_setpoint, in.heating_setpoint, in.occupants,
  in.lighting, in.misc_extra_refrigerator, in.misc_pool_pump,
  in.misc_gas_fireplace, in.range_spot_vent_hour,
  in.hot_water_fixtures, in.vacancy_status
)])
y <- final_merged_data$electricity

# Convert to DMatrix
ddata <- xgb.DMatrix(data = x, label = y)

# Train XGBoost model
xgb_model_behavioural <- xgboost(
  data = ddata, max_depth = 6, eta = 0.1, nrounds = 100,
  objective = "reg:squarederror"
)

# Display model
print(xgb_model_behavioural)
summary(xgb_model_behavioural)
```
# Predict 
```{r}
linear_preds_behavioural <- predict(linear_model_behavioural, newdata = test_data)

# Evaluate Linear Regression
evaluate_model <- function(actual, predicted) {
  mse <- mean((actual - predicted)^2)
  mae <- mean(abs(actual - predicted))
  r2 <- 1 - (sum((actual - predicted)^2) / sum((actual - mean(actual))^2))
  return(list(MSE = mse, MAE = mae, R2 = r2))
}

linear_results_behavioural <- evaluate_model(test_data$electricity, linear_preds_behavioural)
linear_results_behavioural

```

```{r}
library(BayesFactor)
library(xgboost)
library(stats)

# Combine all 40 variables into the formula
formula <- as.formula(
  "electricity ~ building_id + in.geometry_floor_area + in.geometry_stories +
  in.vintage + in.geometry_garage + in.ceiling_fan + in.insulation_slab +
  in.ducts + in.roof_material + in.tenure +
  dry_bulb_temperature + relative_humidity + wind_speed +
  wind_direction + global_horizontal_radiation + direct_normal_radiation +
  diffuse_horizontal_radiation + in.weather_file_latitude +
  in.weather_file_longitude + in.weather_file_city +
  in.insulation_ceiling + in.insulation_floor + in.insulation_wall +
  in.windows + in.water_heater_efficiency + in.heating_setpoint_offset_magnitude +
  in.cooling_setpoint_offset_magnitude + in.insulation_foundation_wall +
  in.hvac_heating_efficiency + in.hvac_cooling_efficiency +
  in.cooling_setpoint + in.heating_setpoint + in.occupants + in.lighting +
  in.misc_extra_refrigerator + in.misc_pool_pump + in.misc_gas_fireplace +
  in.range_spot_vent_hour + in.hot_water_fixtures + in.vacancy_status"
)

# Prepare the dataset
# Ensure only required variables are included
data <- final_merged_data[, all.vars(formula), with = FALSE]

# XGBoost Model
x <- as.matrix(data[, -c("electricity"), with = FALSE])
y <- data$electricity
ddata <- xgb.DMatrix(data = x, label = y)

xgb_model <- xgboost(
  data = ddata,
  max_depth = 6,
  eta = 0.1,
  nrounds = 100,
  objective = "reg:squarederror"
)

cat("XGBoost Model Summary:\n")
print(xgb_model)

# Linear Regression Model
linear_model <- lm(formula, data = data)

cat("\nLinear Regression Model Summary:\n")
summary(linear_model)

# Bayesian Regression Model
bayesian_model <- lmBF(formula, data = data)

cat("\nBayesian Regression Model Summary:\n")
print(bayesian_model)
```

